### ISSUE TITLE
[Balance] Agregar exportación en PDF

### ISSUE THREAD

**Issue by nicolasdimarco** [fiqus/coobs#206]
Hoy en día el balance se exporta solo en formato imagen, habría que en principio pasarlo a PDF.
Se podría abrir en varias tareas:
- [ ] generar PDF blanco
- [ ] agregar contenido al PDF
- [ ] darle formato al contenido

**Comment by diegomanuel** [comment]
Hecho en #325! Ver detalles ahí.
