### ISSUE TITLE
Proteger de ataques XSS

### ISSUE THREAD

**Issue by mjvallone** [fiqus/coobs#236]
en la descripción se puede completar con texto enriquecido, hay que sanitizar para prevenir ataques

ejemplos:  https://portswigger.net/web-security/cross-site-scripting/cheat-sheet

`curl 'https://coobs.io/api/actions/28/' \                                                                                                                            
  -X 'PUT' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTk3MjU1OTc2LCJqdGkiOiJiYTdkOGNlYjlkNjY0YjBhOTVlZTNlZjQyMjA5YjhkZiIsInVzZXJfaWQiOjQ3LCJ1c2VyIjp7ImlkIjo0NywidXNlcm5hbWUiOiJtbGFtYmlyQGZpcXVzLmNvb3AiLCJmaXJzdE5hbWUiOiJNYXJpYW5vIiwibGFzdE5hbWUiOiJMYW1iaXIiLCJjb29wZXJhdGl2ZUlkIjoyLCJlbWFpbCI6Im1sYW1iaXJAZmlxdXMuY29vcCIsImhvdXJzVG9JbnZlc3QiOiIwLjAifSwiY29vcGVyYXRpdmUiOnsiaWQiOjIsIm5hbWUiOiJGaXF1cyIsImJ1c2luZXNzTmFtZSI6IkNvb3BlcmF0aXZhIGRlIFRyYWJham8gRmlxdXMgTFREQSIsInN0YXJ0aW5nRGF0ZSI6IjIwMTEtMTItMjMiLCJpc0FjdGl2ZSI6ZmFsc2UsInN1c3RhaW5hYmxlRGV2ZWxvcG1lbnRHb2Fsc0FjdGl2ZSI6ZmFsc2V9fQ.b8yetMU-V217wAFqZGC-Fv3Fy8QRtV59qwAFcsrljVg' \
  -H 'Accept-Language: en' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://coobs.io' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://coobs.io/app/' \
  --data-binary '{"id":28,"partnersInvolved":[{"id":47,"name":"Mariano Lambir","firstName":"Mariano","lastName":"Lambir"}],"principles":[{"id":1,"name":"Open and voluntary membership","nameKey":"openAndVoluntary","description":"Las cooperativas son organizaciones voluntarias, abiertas a todas las personas que puedan utilizar sus servicios y que estén dispuestas a aceptar las responsabilidades de ser miembros, sin discriminación de género, social, racial, política o religiosa.","descriptionKey":"openAndVoluntaryDesc","visible":true,"mainPrinciple":1,"cooperative":2}],"sustainableDevelopmentGoals":[],"investedMoney":"0.00","investedHours":"0.00","date":"2020-08-12","name":"test xss","description":"“test” test 123 **asdasd** \"\" [Click Me](javascript:alert())","public":true,"cooperative":2}' \
  --compressed`

poner editor markdown de una y deshabilitar todo lo posible
https://dotdev.co/tiptap-wysiwyg/

**Comment by diegomanuel** [comment]
@mlambir cuando puedas trata de romperlo todo porfa!! :bomb:

**Comment by mjvallone** [comment]
Haría falta revisar por completo los arreglos que se hicieron

**Comment by diegomanuel** [comment]
Estuve haciendo varios intentos más siguiendo algunos ejemplos de https://portswigger.net/web-security/cross-site-scripting/cheat-sheet y metiendo algunas variantes mías, pero siempre respondió bien y el contenido fue limpiado en `description`.
Para otros campos como el `name` de la action, no se limpia nada pero al momento de mostrar en pantalla se muestra como texto y NO como html, así que no hay problema en ppio...

Cierro este issue ya que no creo que vaya a haber más investigación o avances en el asunto.
